//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquinas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aquinas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.my.aquinas.ac.uk/MobileAPI/api/{0}/{1}.
        /// </summary>
        internal static string ApiTemplateUrl {
            get {
                return ResourceManager.GetString("ApiTemplateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.my.aquinas.ac.uk/MobileAPI/api/Auth/GetToken.
        /// </summary>
        internal static string AuthenticationUrl {
            get {
                return ResourceManager.GetString("AuthenticationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string ExceptionBadLogin {
            get {
                return ResourceManager.GetString("ExceptionBadLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected status: {0}.
        /// </summary>
        internal static string ExceptionBadStatus {
            get {
                return ResourceManager.GetString("ExceptionBadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No root tag present or otherwise malformed XML..
        /// </summary>
        internal static string ExceptionMalformedXml {
            get {
                return ResourceManager.GetString("ExceptionMalformedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AuthenticationInfo object has not yet been authenticated. Use the BeginAuthenticate method to authenticate..
        /// </summary>
        internal static string ExceptionNotYetAuthenticated {
            get {
                return ResourceManager.GetString("ExceptionNotYetAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s chosen name not present in the document..
        /// </summary>
        internal static string ExceptionStudentNameNotPresent {
            get {
                return ResourceManager.GetString("ExceptionStudentNameNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A token was not received from the server..
        /// </summary>
        internal static string ExceptionTokenNotReceived {
            get {
                return ResourceManager.GetString("ExceptionTokenNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.datacontract.org/2004/07/Aquinas.MobileAPI.Controllers.
        /// </summary>
        internal static string XmlNamespace {
            get {
                return ResourceManager.GetString("XmlNamespace", resourceCulture);
            }
        }
    }
}
